@startuml Pokemon EXP Level-Up System

start

:Battle Result = Win;

:Call ExpCalculator.CalculateExpGain();

:Add EXP to Current Pokemon;

if (CanLevelUp?) then (Yes)
  :Increase Level;
  :Check Learn New Move;
  :Check Evolution;
else (No)
endif

:PlayerRepository.Save();

:Return to StoryScreen;

stop
@enduml